import { NextRequest, NextResponse } from 'next/server';
import mammoth from 'mammoth';
import JSZip from 'jszip';

type Provider='groq'|'openai'|'anthropic'|'google';
function providerFromName(value:unknown):Provider{if(value==='openai'||value==='anthropic'||value==='google')return value;return 'groq';}
type Msg={role:'user'|'assistant'|'system';content:any};
const FILE_RE=/\[\[SUDOAI_(IMAGE|FILE)\s+name="([^"]*)"\s+type="([^"]*)"\s+data="(data:[^"]+)"\]\]/g;
function base64FromDataUrl(data:string){const i=data.indexOf(',');return i>=0?Buffer.from(data.slice(i+1),'base64'):Buffer.alloc(0)}
function ext(name:string){return name.toLowerCase().split('.').pop()||''}
async function extractDocument(name:string,type:string,data:string){const buffer=base64FromDataUrl(data);const e=ext(name);if(e==='docx'){const out=await mammoth.extractRawText({buffer});return out.value.slice(0,120000)}if(e==='pdf'){try{const pdfjs=await import('pdfjs-dist/legacy/build/pdf.mjs');const loadingTask=pdfjs.getDocument({data:new Uint8Array(buffer)} as any);const doc=await loadingTask.promise;const pages:string[]=[];for(let n=1;n<=doc.numPages&&pages.join('\n').length<120000;n++){const page=await doc.getPage(n);const content=await page.getTextContent();pages.push(content.items.map((item:any)=>typeof item.str==='string'?item.str:'').join(' '));}await doc.destroy();return pages.join('\n\n').slice(0,120000)}catch(error){console.error('PDF extraction failed:',error);return`PDF attached: ${name}. The PDF text extractor could not run on this deployment, but the file was received successfully.`}}if(e==='zip'){const zip=await JSZip.loadAsync(buffer);const parts:string[]=[];for(const[path,entry]of Object.entries(zip.files)){if(entry.dir)continue;const x=ext(path);if(['txt','md','csv','json','js','jsx','ts','tsx','py','java','c','cpp','h','hpp','cs','go','rs','php','rb','swift','kt','sql','html','css','scss','xml','yaml','yml','toml','sh','bash','env','log'].includes(x))parts.push(`--- ${path} ---\n${await entry.async('text')}`);if(parts.join('\n').length>120000)break}return parts.join('\n\n').slice(0,120000)||`ZIP archive attached: ${name}. No supported text/code files were found inside.`}return`Attached file: ${name} (${type||e}).`}
async function normalizeMessages(messages:Msg[],provider:Provider){const out:Msg[]=[];for(const original of messages){if(typeof original.content!=='string'){out.push(original);continue}const text=original.content;if(original.role!=='user'||!text.includes('[[SUDOAI_')){out.push(original);continue}const parts:any[]=[];let last=0;let match:RegExpExecArray|null;FILE_RE.lastIndex=0;while((match=FILE_RE.exec(text))){const before=text.slice(last,match.index);if(before.trim())parts.push({type:'text',text:before});const kind=match[1],name=match[2],type=match[3],data=match[4];if(kind==='IMAGE')parts.push({type:'image_url',image_url:{url:data}});else parts.push({type:'text',text:`\n[Attached document ${name}]\n${await extractDocument(name,type,data)}\n[End attached document]\n`});last=match.index+match[0].length}const after=text.slice(last);if(after.trim())parts.push({type:'text',text:after});if(provider==='anthropic'){const anthropicParts=parts.map(p=>p.type==='image_url'?{type:'image',source:{type:'base64',media_type:p.image_url.url.split(';')[0].slice(5),data:p.image_url.url.split(',')[1]}}:p);out.push({role:'user',content:anthropicParts})}else out.push({role:'user',content:parts})}return out}

export async function POST(req:NextRequest){try{const{messages,provider:providerValue='groq',model}=await req.json();if(!Array.isArray(messages))return NextResponse.json({error:'messages must be an array'},{status:400});const provider=providerFromName(providerValue);const actualModel=typeof model==='string'&&model.trim()?model.trim():provider==='groq'?'llama-3.1-8b-instant':provider==='openai'?'gpt-5.6':provider==='anthropic'?'claude-sonnet-4-5':'gemini-2.5-flash';const apiKey=provider==='openai'?process.env.OPENAI_API_KEY:provider==='anthropic'?process.env.ANTHROPIC_API_KEY:provider==='google'?process.env.GEMINI_API_KEY:process.env.GROQ_API_KEY;const providerLabel=provider==='openai'?'OpenAI':provider==='anthropic'?'Anthropic':provider==='google'?'Google':'Groq';if(!apiKey)return NextResponse.json({error:`${providerLabel} API key is not configured.`},{status:500});const normalized=await normalizeMessages(messages as Msg[],provider);let response:Response;
if(provider==='anthropic'){const system=normalized.find(m=>m.role==='system')?.content;const chatMessages=normalized.filter(m=>m.role!=='system').map(m=>({role:m.role==='assistant'?'assistant':'user',content:m.content}));response=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'Content-Type':'application/json','x-api-key':apiKey,'anthropic-version':'2023-06-01'},body:JSON.stringify({model:actualModel,max_tokens:2048,...(system?{system}:{}),messages:chatMessages})})}
else if(provider==='google'){const contents=normalized.filter(m=>m.role!=='system').map(m=>({role:m.role==='assistant'?'model':'user',parts:Array.isArray(m.content)?m.content.map((p:any)=>p.type==='text'?{text:p.text}:p.type==='image_url'?{inlineData:{mimeType:p.image_url.url.split(';')[0].slice(5),data:p.image_url.url.split(',')[1]}}:{text:String(p.text||'')}):[{text:String(m.content)}]}));response=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(actualModel)}:generateContent?key=${encodeURIComponent(apiKey)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contents,generationConfig:{temperature:0.7,maxOutputTokens:2048}})})}
else{const endpoint=provider==='openai'?'https://api.openai.com/v1/chat/completions':'https://api.groq.com/openai/v1/chat/completions';response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${apiKey}`},body:JSON.stringify({model:actualModel,messages:normalized,temperature:0.7,max_tokens:2048})})}
const raw=await response.text();let data:any=null;try{data=raw?JSON.parse(raw):null}catch{data=null}if(!response.ok)return NextResponse.json({error:data?.error?.message||data?.error?.status||raw?.slice(0,500)||`${providerLabel} API request failed.`},{status:response.status});if(!data)return NextResponse.json({error:`${providerLabel} returned an empty response.`},{status:502});const message=provider==='anthropic'?data.content?.filter((b:{type?:string})=>b.type==='text').map((b:{text:string})=>b.text).join('\n')||'':provider==='google'?data.candidates?.[0]?.content?.parts?.filter((p:{text?:string})=>typeof p.text==='string').map((p:{text:string})=>p.text).join('')||'':data.choices?.[0]?.message?.content||'';return NextResponse.json({message,usage:data.usageMetadata||data.usage||null,model:data.modelVersion||data.model||actualModel,provider:providerLabel,modelLabel:data.modelVersion||data.model||actualModel})}catch(error){console.error('SudoAI chat error:',error);return NextResponse.json({error:error instanceof Error?error.message:'Unable to process the request.'},{status:500})}}
