'use client';
import { useEffect, useState } from 'react';
import { supabase } from '../../lib/supabase';

type Key={id:string;token_prefix:string;created_at:string;last_used_at:string|null;revoked_at:string|null};

export default function ProfilePage(){
  const [email,setEmail]=useState(''); const [keys,setKeys]=useState<Key[]>([]); const [newKey,setNewKey]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  async function authHeader(){const {data}=await supabase!.auth.getSession(); return data.session?.access_token||''}
  async function load(){if(!supabase)return; const {data}=await supabase.auth.getSession(); if(!data.session){location.href='/';return} setEmail(data.session.user.email||''); const token=data.session.access_token; const r=await fetch('/api/cli-key',{headers:{Authorization:`Bearer ${token}`}}); const d=await r.json(); if(r.ok)setKeys(d.keys||[]); else setError(d.error||'Unable to load keys.');}
  useEffect(()=>{load()},[]);
  async function createKey(){setBusy(true);setError('');setNewKey(''); try{const token=await authHeader(); const r=await fetch('/api/cli-key',{method:'POST',headers:{Authorization:`Bearer ${token}`}}); const d=await r.json(); if(!r.ok)throw new Error(d.error||'Unable to create key.'); setNewKey(d.token); await load()}catch(e){setError(e instanceof Error?e.message:'Unable to create key.')}finally{setBusy(false)}}
  async function revoke(id:string){setBusy(true);try{const token=await authHeader(); await fetch('/api/cli-key',{method:'DELETE',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({id})}); await load()}finally{setBusy(false)}}
  return <main style={{minHeight:'100vh',background:'#070a0f',color:'#f5f7fa',fontFamily:'Inter,system-ui,sans-serif'}}><div style={{maxWidth:820,margin:'0 auto',padding:'48px 24px 100px'}}><a href="/" style={{color:'#aeb8c6',textDecoration:'none'}}>← Back to SudoAI</a><h1 style={{fontSize:48,margin:'44px 0 8px'}}>Profile</h1><p style={{color:'#9ba8b8',marginBottom:32}}>{email}</p><section style={{background:'#0c1118',border:'1px solid #1d2631',borderRadius:18,padding:28}}><h2 style={{marginTop:0}}>SudoAI CLI access</h2><p style={{color:'#aeb8c6',lineHeight:1.7}}>Create a personal CLI API key, copy it once, and add it to the SudoAI CLI. The key lets the CLI use your SudoAI account and its normal model/usage permissions. The full key is only shown when it is created.</p><button onClick={createKey} disabled={busy} style={{padding:'11px 16px',borderRadius:10,border:0,cursor:'pointer'}}>＋ Create CLI key</button>{newKey&&<div style={{marginTop:18}}><p style={{color:'#ffd166'}}>Copy this key now. It will not be shown again.</p><code style={{display:'block',padding:14,background:'#05070a',border:'1px solid #28313d',borderRadius:10,overflowX:'auto'}}>{newKey}</code><p style={{color:'#8f9baa'}}>Then run <code>sudoai</code> and configure <code>SUDOAI_API_KEY</code> with this value.</p></div>}{error&&<p style={{color:'#ff7b7b'}}>{error}</p>}<div style={{marginTop:28,display:'grid',gap:10}}>{keys.map(k=><div key={k.id} style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:16,padding:'14px 0',borderTop:'1px solid #1d2631'}}><div><b>{k.token_prefix}…</b><div style={{fontSize:13,color:'#7f8b99'}}>Created {new Date(k.created_at).toLocaleDateString()} {k.revoked_at?'· Revoked':''}</div></div>{!k.revoked_at&&<button onClick={()=>revoke(k.id)} disabled={busy} style={{background:'transparent',color:'#ff8585',border:'1px solid #51343a',borderRadius:8,padding:'7px 11px'}}>Revoke</button>}</div>)}</div></section></div></main>}
