export const metadata = { title: 'SudoAI Code for VS Code', description: 'User documentation for SudoAI Code, the SudoAI coding agent for VS Code.' };

const sections = [
  ['Install the development build', <>Until the Marketplace package is published, clone the repository and build the extension locally.</>],
  ['Start SudoAI', <>Open the VS Code Chat view and use <code>@sudo</code>. Try requests such as <code>@sudo inspect this project</code>, <code>@sudo find the authentication bug</code>, or <code>@sudo run the tests and fix failures</code>.</>],
  ['Slash commands', <>Use <code>@sudo /fix</code>, <code>@sudo /review</code>, and <code>@sudo /test</code> for common coding-agent workflows.</>],
  ['What SudoAI can do', <>SudoAI can read files, list directories, search code, write files, and run shell commands. File changes and shell commands require approval.</>],
  ['Configure your account', <>Open Settings → Extensions → SudoAI. Configure the SudoAI API URL, API key if required, model, and maximum tool steps. Never share or commit an API key.</>],
  ['How the agent works', <>For a request such as <code>@sudo fix the authentication bug</code>, the agent can inspect the workspace, propose local actions, edit files, run tests, inspect results, and return a final answer. Local files and terminal commands are executed by the extension, not on the SudoAI server.</>],
  ['Safety', <>The first version asks before writing a file or running a shell command. Workspace operations are restricted to the currently opened workspace. Do not approve commands you do not understand.</>],
];

export default function VSCodeDocs(){return <main style={{minHeight:'100vh',background:'#070a0f',color:'#f5f7fa',fontFamily:'Inter,system-ui,sans-serif'}}><div style={{maxWidth:920,margin:'0 auto',padding:'56px 24px 100px'}}><a href="/" style={{color:'#a8b3c2',textDecoration:'none'}}>← Back to SudoAI</a><div style={{marginTop:48}}><div style={{display:'inline-flex',padding:'7px 12px',border:'1px solid #26303c',borderRadius:999,color:'#9ba8b8',fontSize:13}}>SudoAI Developer Tools</div><h1 style={{fontSize:'clamp(38px,7vw,64px)',lineHeight:1.05,margin:'20px 0 16px',letterSpacing:'-2px'}}>SudoAI Code for VS Code</h1><p style={{fontSize:20,lineHeight:1.6,color:'#aeb8c6',maxWidth:720}}>A coding agent inside VS Code. Inspect your workspace, search code, edit files, run tests, and work through coding tasks with SudoAI.</p></div><div style={{marginTop:42,display:'grid',gap:18}}>{sections.map(([title,body])=><section key={title as string} style={{border:'1px solid #1d2631',background:'#0c1118',borderRadius:18,padding:'26px 28px'}}><h2 style={{fontSize:23,margin:'0 0 13px'}}>{title as string}</h2><div style={{color:'#b6c0cd',fontSize:16,lineHeight:1.75}}>{body}</div></section>)}</div><section style={{marginTop:18,border:'1px solid #1d2631',background:'#0c1118',borderRadius:18,padding:28}}><h2 style={{fontSize:23,marginTop:0}}>Install</h2><pre style={{overflowX:'auto',background:'#05070a',border:'1px solid #202833',padding:18,borderRadius:12,color:'#dce4ee'}}><code>{`git clone https://github.com/sudobuildorg/sudoai.git\ncd sudoai/vscode\nnpm install\nnpm run compile`}</code></pre><p style={{color:'#b6c0cd',lineHeight:1.7}}>Open <code>sudoai/vscode</code> in VS Code and press F5. A new Extension Development Host window opens. Open your coding project in that window.</p></section><section style={{marginTop:18,border:'1px solid #1d2631',background:'#0c1118',borderRadius:18,padding:28}}><h2 style={{fontSize:23,marginTop:0}}>Troubleshooting</h2><p style={{color:'#b6c0cd',lineHeight:1.7}}>If SudoAI returns an empty response, check the API URL and that <code>/api/chat</code> is available. If authentication fails, configure a valid API key when your deployment requires one. If the agent cannot see your project, make sure the project folder is opened as the VS Code workspace.</p></section><footer style={{marginTop:42,color:'#6f7b89',fontSize:13}}>SudoAI · VS Code documentation</footer></div></main>}
